remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Welcome to my page]
description: [My name is pinglei. I am an IBI1 student at ZJU-UoE institute, Zhejiang University]
